development:
  adapter: postgresql
  encoding: unicode
  database: income_tracking_development
  pool: 5
  username: kirill
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: income_tracking_test
  pool: 5
  username: kirill
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: income_tracking_production
  pool: 5
  username: kirill
  password:
